project:
  name: example

data:
  training:
    path: "path/to/training/data"

models:
  - name: example_model
    type: example_type

    hyperparameters:
      learning_rate: 0.01

    optimizer:
      name: example_optimizer

      hyperparameters:
        batch_size: 32

validation:
  split: 0.2
